package com.redhat.weightwatcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OptInOut implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Program ID")
   private java.lang.Integer programid;
   @org.kie.api.definition.type.Label(value = "User ID")
   private java.lang.Integer userid;
   @org.kie.api.definition.type.Label(value = "Rule Name")
   private java.lang.String rulename;

   public OptInOut()
   {
   }

   public java.lang.Integer getProgramid()
   {
      return this.programid;
   }

   public void setProgramid(java.lang.Integer programid)
   {
      this.programid = programid;
   }

   public java.lang.Integer getUserid()
   {
      return this.userid;
   }

   public void setUserid(java.lang.Integer userid)
   {
      this.userid = userid;
   }

   public java.lang.String getRulename()
   {
      return this.rulename;
   }

   public void setRulename(java.lang.String rulename)
   {
      this.rulename = rulename;
   }

   public OptInOut(java.lang.Integer programid, java.lang.Integer userid,
         java.lang.String rulename)
   {
      this.programid = programid;
      this.userid = userid;
      this.rulename = rulename;
   }

}
